version: '3.8'
# 使用するDockerEngineリソースに適応するバージョンを指定する。

services:
  apex-bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        APEX_API_KEY: ${APEX_API_KEY}
        TWITTER_API_KEY: ${TWITTER_API_KEY}
        TWITTER_API_KEY_SECRET: ${TWITTER_API_KEY_SECRET}
        TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
        TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
        TWITTER_ACCOUNT_ID: ${TWITTER_ACCOUNT_ID}
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/code/
      - ${PIP_CACHE_DIR_BOT:-cache-bot}:/root/.cache


volumes:
  cache-bot: